language: python

python:
    - 2.6
    - 2.7

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda

install:
    # Create a new environment
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION pip cython nose
    - source activate test

    # Now install dependencies
    - conda install --yes h5py
    - conda install --yes numpy
    - conda install --yes scipy
    - conda install --yes matplotlib
    - conda install --yes scikit-image
    - conda install --yes astropy
    - conda install --yes networkx

script:
    - python setup.py install
    - nosetests fil_finder/tests/