language: python

sudo: false

python:
    - 2.6
    - 2.7

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

install:
    # Create a new environment
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION pip cython nose
    - source activate test

    # Now install dependencies
    - conda install --yes h5py numpy scipy matplotlib scikit-image astropy networkx

script:
    - python setup.py install
    - nosetests fil_finder/tests/