language: python

sudo: false

python:
    - 2.7

# The apt packages below are needed for sphinx builds. A full list of packages
# that can be included can be found here:
#
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        - SETUP_CMD='test'
        - CONDA_ADDITIONAL='scipy matplotlib networkx h5py'
        - NP_VER=1.10
        - ASTRO_VER=1.0
        - SKIMG_VER=1.12
    matrix:
        - SETUP_CMD='egg_info'

matrix:
    include:
        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        # - python: 2.7
        #   env: SETUP_CMD='build_sphinx -w'

        - python: 2.7
          env: NP_VER=1.9 ASTRO_VER=1.0 SKIMG_VER=1.12

        - python: 2.7
          env: NP_VER=1.10 ASTRO_VER=1.0 SKIMG_VER=1.12

        - python: 2.7
          env: NP_VER=1.10 ASTRO_VER=1.1 SKIMG_VER=1.12

        - python: 2.7
          env: NP_VER=1.11 ASTRO_VER=1.2 SKIMG_VER=1.12

        - python: 2.7
          env: NP_VER=1.11 ASTRO_VER=1.2 SKIMG_VER=1.12

        - python: 2.7
          env: NP_VER=1.12 ASTRO_VER=1.3 SKIMG_VER=1.13

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

install:
    # Create a new environment
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION pip cython pytest
    - source activate test

    # Now install dependencies
    - conda install --yes $CONDA_ADDITIONAL
    - conda install --yes numpy=$NP_VER astropy=$ASTRO_VER scikit-image=$SKIMG_VER

script:
    - python setup.py $SETUP_CMD